### ISSUE TITLE
feature request: download all files of current folder

### ISSUE THREAD

**Issue by kumboleijo** [dannyedel/nginx-dirindex#4]
* allow users do download all files within a folder with 1-click (so you don't have to press x-times ***download***) @dannyedel

**Comment by dannyedel** [comment]
While this would be nice, I don't see any way on how to implement this server-side.  Downloading (single or multiple files) is a client-side operation, so it can only be triggered by the client.

I don't know any browser that has a multiple-download functionality out-of-the-box, I assume whatever page offers this does it in JavaScript or AdobeFlash.

AFAIK It only works if the browser is set to download files without even asking the user for a name or storage location (a behaviour that annoys me personally, so I have it off on all my browsers anyway...)

I don't understand enough (or anything, for that matter) about JavaScript to do this myself, but if you feel comfortable I will accept a pullrequest containing JS code that does the trick.

**Comment by dannyedel** [comment]
You can of course use `wget`'s multidownload ability...

Oneliner (assuming `$URL` has the format `https://username:password@hostname/path/to/dir/`)

```bash
 wget -e robots=off -r -np -nd -c --reject-regex '\?' $URL
```

Magic Sauce List (see `man wget` for more)
* `-e robots=off` Ignore robots.txt (needed for my non-public server)
* `-r` download recursive
* `-np` do *not* download parent directories
* `-nd` do *not* create a directory subtree mirroring the server's
* `-c` continue partial downloads / skip already downloaded files
